### PR TITLE
Language files for French and Polish

### PR DESCRIPTION
**Pull request by ms-studio**
Adding language files for French (100%) and Polish (just the four strings visible on the dashboard).

### CODE REVIEW

**Comment by swissspidy** [comment]
Hey Manuel, thanks for the PR!

Can you add these translations directly on WordPress.org?

See https://translate.wordpress.org/locale/fr-fr/default/wp-plugins/statify and https://translate.wordpress.org/locale/pl/default/wp-plugins/statify

**Comment by ms-studio** [comment]
Hey Pascal, 

Great to see that Statify is taken care of by such an amazing team :)

I just added the new translations to translate.wordpress.org ... will nudge @fxbenard so they get validated.

**Comment by fxbenard** [comment]
https://translate.wordpress.org/projects/wp-plugins/statify/dev/fr/default Validated!
Well done guys!

**Comment by ms-studio** [comment]
Thanks Fx! 

Closing the PR, since with the new wordpress.org translation system we don't need those .po/.mo files.

**Pull request closed without merging**
