### PR TITLE
update paypal links for donations

### PR DESCRIPTION
**Pull request by Drivingralle**

### CODE REVIEW

**Comment by ghost** [comment]
As this project now includes links to both Sergej and pluginkollektiv, I wouldn't mind some notification somewhere about which Paypal account this actually is?

As this is a collective, should there be a donation link in the first place?

**Comment by Drivingralle** [comment]
@corvannoorloos The right target account it the one by the pluginkollektiv.

At which line do you still find the link to Sergejs account? 
I may missed to replace it.

**Comment by ghost** [comment]
@Drivingralle I believe all Paypal links are handled in this commit, but there still are the remaining Flattr links and the links to Sergej's wiki.

This all together I guess can be a bit confusing.

**Comment by Drivingralle** [comment]
@corvannoorloos  Flattr and Amazon links in all plugins will be addressed soon. 

Thanks for reminding.

**Comment by ghost** [comment]
@Drivingralle :+1:

**Pull request closed without merging**
