### PR TITLE
Update changelog and version number to 1.6.1

### PR DESCRIPTION
**Pull request by patrickrobrecht**

### CODE REVIEW

**Review by bueltge — APPROVED** [review]

**Comment by bueltge** [comment]
@patrickrobrecht Where are the changes for this adding in the changelog? It is merged before?

**Comment by patrickrobrecht** [comment]
The changelog entries added by this PR are for the commits merged into master since the last release, but not added to the changelog.

**Comment by bueltge** [comment]
Ah ok. Than we should merge quickly. ;)

**Comment by bueltge** [comment]
Now, a SVN Upload on wp.org is necessary. @patrickrobrecht can you do that?

**Comment by patrickrobrecht** [comment]
I'll do that in the evening.

**Pull request merged**
