### PR TITLE
prepare release 1.8.4

### PR DESCRIPTION
**Pull request by stklcode**
* add relevant entries to changelog
* raise version to 1.8.4 in _statify.php_
* raise stable version to 1.8.4 in _readme.txt_
* declare compatibility with WordPress 6.1 in _readme.txt_

Compatibility should be tested one last time, then we should be good to go for the maintenance release.

### CODE REVIEW

**Comment by stklcode** [comment]
Tested on a WP 6.0 / PHP 8.0 and WP 6.1 / PHP 8.1 site both WP_DEBUG enabled without any issues.

**Review by Zodiac1978 — CHANGES_REQUESTED** [review]
Little typo "abd" -> "and" in upgrade notice of readme.txt

It seems you forgot to raise the version number in the statify.php plugin header

**Comment by stklcode** [comment]
And that's why Friday-evening-changes always benefit from a second pair of eyes :see_no_evil: 

Should be fixed now.

**Review by Zodiac1978 — APPROVED** [review]
LGTM!

**Pull request merged**
